# Generated by Django 2.1.7 on 2019-03-19 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20190319_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='ingredient',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='recipes',
            old_name='recipe',
            new_name='instruction',
        ),
    ]
